name: Version

on:
  push:
      branches: [ "develop" ]
  pull_request:
      branches: [ "develop" ]
      types: closed

jobs:
  update:
    if: github.event.pull_request.merged == 'true'
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
      with:
        fetch-depth: 0
    - name: Make version file
      run: |
        VERSION=$(git describe)
        MAJOR=$(echo $VERSION | grep -o '^[0-9]*.[0-9]*.[0-9]*')
        MINOR=$(echo $VERSION |  grep -o '\-[0-9]*' | head -1)
        echo $MAJOR$MINOR > ./config/version
        cat ./config/version

    - name: Commit amend
      run: |
          git config --global user.email "jam2in@jam2in.com"
          git config --global user.name "jam2in"
          git add *
          git commit --amend --no-edit
          git push --force-with-lease
